server:
  port: 8081
spring:
  application:
    name: UserService


resilience4j:
  circuitbreaker:
    instances:
      backendA:
        failureRateThreshold: 50
        minimumNumberOfCalls: 20
        permittedNumberOfCallsInHalfOpenState: 3